import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import screen from "../public/screen.png";
import hello from "../public/boy.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import you from "../public/you.png";
import homes from "../public/homes.png";
import tum from "../public/tum.png";
import course from "../public/course.png";
import search from "../public/search.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>IntroPage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">DevByShashank</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://shashankranjan-dev.onrender.com/"
                >
                  Who I AM?
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600  font-burtons font-bold dark:text-teal-400 md:text-6xl">
              Shashank Ranjan
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Mern / Mean Stack Developer and UI/UX designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            HTML, CSS, Javascript, Github, Python, C++, ReactJs, AngularJs, ExpressJs, MongoDB, NodeJs,
            Bootstrap, Tailwind-CSS, NextJs
            </p>
            <div className="text-5xl flex justify-center gap-10 py-3 text-gray-600 dark:text-gray-600 ">
            <a href="https://twitter.com/KingShashank30"> <AiFillTwitterCircle /></a>
            <a href="https://www.linkedin.com/in/shashankranjan/"> <AiFillLinkedin /></a>
              <a href="https://github.com/shashankranjan-dev"><AiFillGithub /></a>

            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 transition ease-in-out delay-150 hover:-translate-y-2 hover:scale-110 duration-700 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={hello} layout="" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-5xl mt-16 text-center text-teal-600 font-bold dark:text-teal-600 ">About Shashank</h3>
            <p className="text-xs py-5 text-center leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-lg">
              I am currently undergraduate student at
              Calcutta Institute Of Engineering & Management. I am a self-taught developer and designer.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center  p-10 rounded-xl my-10 transition ease-in-out delay-150 hover:-translate-y-2 hover:scale-80 duration-300 hover:bg-slate-200 dark:hover:bg-lime-200 dark:bg-white flex-1" style={{boxShadow:"2px 2px 4px gray"}}>
              <Image src={design} width={100} height={100} />
              <h3 className="text-2xl font-bold pt-8 pb-2  ">
                UI/UX
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 font-bold text-teal-600"> Design Tools That i use :</h4>
              <p className="text-gray-800 font-semibold py-1">Figma</p>
              <p className="text-gray-800 font-semibold py-1">Photoshop</p>
              <p className="text-gray-800 font-semibold py-1">Illustrator</p>
              <p className="text-gray-800 font-semibold py-1">Indesign</p>
  
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 transition ease-in-out delay-150 hover:-translate-y-2 hover:scale-80 duration-300 hover:bg-slate-200 dark:hover:bg-lime-200 dark:bg-white flex-1"style={{boxShadow:"2px 2px 4px gray"}}>
              <Image src={code} width={100} height={100} />
              <h3 className="text-2xl font-bold pt-8 pb-2 ">
                Coding Platforms
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 font-bold text-teal-600">Editors That i use :</h4>
              <p className="text-gray-800  font-semibold py-1">VsCode</p>
              <p className="text-gray-800 font-semibold py-1">Atom</p>
              <p className="text-gray-800 font-semibold py-1">Brackets</p>
              <p className="text-gray-800 font-semibold py-1">Sublime Text</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 transition ease-in-out delay-150 hover:-translate-y-2 hover:scale-80 duration-300 hover:bg-slate-200 dark:hover:bg-lime-200 dark:bg-white flex-1"style={{boxShadow:"2px 2px 4px gray"}}>
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-2xl font-bold pt-8 pb-2 ">Services</h3>
              <p className="py-2">
                Are you interested for your current project? I am 
                open to consulting opportunities.
              </p>
              <h4 className="py-4 font-bold text-teal-600">What I Provide :</h4>
              <p className="text-gray-800 font-semibold py-1">Freelancing</p>
              <p className="text-gray-800 font-semibold py-1">Project Guide</p>
              <p className="text-gray-800 font-semibold py-1">Team Leading</p>
              <p className="text-gray-800 font-semibold py-1">Collaborations</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-5xl mt-16 text-center text-teal-600 font-bold dark:text-teal-600  ">Some Of My Creations</h3>
            <p className="text-xs py-5 text-center leading-2 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-lg">
          
            Here listed are some of my projects that I have worked on. 
             You can check them out on my github profile.

            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
            <a href="https://interior-rs94.vercel.app/"> <Image
                className="rounded-lg object-cover transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-700"
                width={"100%"}
                height={"50%"}
                layout="responsive"
                src={screen}
              /></a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://chil-xx-weld.vercel.app/"> <Image
                className="rounded-lg object-cover transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-700"
                width={"100%"}
                height={"50%"}
                layout="responsive"
                src={you}
              /></a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://shashankranjan-dev.github.io/HomeDecoration/"> <Image
                className="rounded-lg object-cover transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-700"
                width={"100%"}
                height={"50%"}
                layout="responsive"
                src={homes}
              /></a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://e-learning-jet.vercel.app/">  <Image
                className="rounded-lg object-cover transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-700"
                width={"100%"}
                height={"50%"}
                layout="responsive"
                src={course}
              /></a>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://shashankranjan-dev.github.io/Full-Stack-E-commerce/?#"> <Image
                className="rounded-lg object-cover transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-700"
                width={"100%"}
                height={"50%"}
                layout="responsive"
                src={tum}
              /></a> 
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://shashankranjan-dev.github.io/Search-Engine/">  <Image
                className="rounded-lg object-cover transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-700"
                width={"100%"}
                height={"50%"}
                layout="responsive"
                src={search}
              /></a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
